### ISSUE TITLE
list out of range

### ISSUE THREAD

**Issue by xlb8** [ch98road/YOLOV3_Tensorrt_Rectangular_Inference#3]
博主你好 在跑程序的时候出现list index out of range是怎么回事呢 使用 和不使用tensorrt模型都存在 但是它俩中断的时候输出的帧数不一样。都是输出了三百多帧就挂掉了。希望能帮帮我，谢谢
![QQ截图20200908221558](https://user-images.githubusercontent.com/56586981/92488345-0205d280-f221-11ea-8f1c-edef7f5cc01a.jpg)

**Comment by cmcamdy** [comment]
能跑起来说明主体没有问题，那么应该考虑这个问题本身，out of range也就两种可能，求组过大，或者下标越界，建议先定位是哪个数组的问题，再做后续测试

**Comment by xlb8** [comment]
谢谢你，昨晚仔细看了一下，找到原因了。感谢感谢

--祝好
